import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#0D0D0D',
        paddingHorizontal: 16,
        paddingTop: 20,
    },
    titulo: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#00CFFF',
        marginBottom: 15,
        textAlign: 'center',
    },
    comentarioContainer: {
        paddingVertical: 12,
        paddingHorizontal: 10,
        backgroundColor: '#1C1F39',
        borderRadius: 12,
        marginBottom: 10,
    },
    comentarioTopo: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    comentarioTexto: {
        fontSize: 16,
        color: '#87AAFF',
        flex: 1,
        paddingRight: 10,
    },
    menuButton: {
        padding: 6,
    },
    menuInline: {
        marginTop: 10,
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 20,
    },
    menuTexto: {
        fontSize: 14,
        color: '#87AAFF',
    },
    semComentarios: {
        textAlign: 'center',
        color: '#aaa',
        marginTop: 40,
        fontStyle: 'italic',
    },
    areaComentario: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        borderTopWidth: 1,
        borderColor: '#2D2D3A',
        backgroundColor: '#0D0D0D',
    },
    input: {
        flex: 1,
        backgroundColor: '#1C1F39',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
        fontSize: 15,
        marginRight: 10,
        color: '#87AAFF',
        borderWidth: 1,
        borderColor: '#2D2D3A',
    },
    botao: {
        backgroundColor: '#00CFFF',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 8,
    },
    botaoDesativado: {
        backgroundColor: '#1C1F39',
        borderWidth: 1,
        borderColor: '#444',
    },
    botaoTexto: {
        color: 'white',
        fontWeight: 'bold',
    },
    edicaoContainer: {
        backgroundColor: '#0D0D0D',
        padding: 20,
        borderRadius: 12,
        width: '90%',
        borderWidth: 1,
        borderColor: '#00CFFF',
    },
    modalInput: {
        height: 100,
        borderColor: '#2D2D3A',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 10,
        textAlignVertical: 'top',
        fontSize: 16,
        marginBottom: 10,
        backgroundColor: '#1C1F39',
        color: '#87AAFF',
    },
    modalBotoes: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    botaoModal: {
        flex: 1,
        padding: 10,
        borderRadius: 8,
        marginHorizontal: 5,
        alignItems: 'center',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        justifyContent: 'center',
        alignItems: 'center',
    },
});
