// estilo/estiloEditarPerfil.js
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    background: {
        flex: 1,
    },
    container: {
        padding: 20,
        paddingBottom: 40,
        alignItems: 'stretch',
        backgroundColor: 'rgba(0,0,0,0.7)',
    },
    avatarPreview: {
        width: 120,
        height: 120,
        borderRadius: 60,
        alignSelf: 'center',
        marginBottom: 20,
        borderWidth: 2,
        borderColor: '#00BFFF',
        backgroundColor: '#111',
    },
    label: {
        fontSize: 16,
        color: '#00BFFF',
        fontWeight: 'bold',
        marginTop: 15,
        marginBottom: 6,
    },
    input: {
        height: 50,
        borderWidth: 1,
        borderColor: '#00BFFF',
        borderRadius: 10,
        paddingHorizontal: 12,
        color: '#fff',
        fontSize: 15,
        backgroundColor: '#1a1a1a',
    },
    botao: {
        backgroundColor: '#00BFFF',
        marginTop: 20,
        paddingVertical: 12,
        alignItems: 'center',
        borderRadius: 10,
        shadowColor: '#00BFFF',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 6,
        elevation: 4,
    },
    botaoAvatar: {
        backgroundColor: '#6f42c1',
        marginTop: 20,
        paddingVertical: 12,
        alignItems: 'center',
        borderRadius: 10,
        shadowColor: '#6f42c1',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 6,
        elevation: 4,
    },
    botaoTexto: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    botaoVoltar: {
        position: 'absolute',
        top: 40,
        left: 20,
        backgroundColor: 'rgba(0,0,0,0.6)',
        paddingVertical: 8,
        paddingHorizontal: 14,
        borderRadius: 20,
        zIndex: 10,
        shadowColor: '#00BFFF',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
        elevation: 5,
    },
    textoVoltar: {
        color: '#00BFFF',
        fontWeight: '700',
        fontSize: 16,
    },
});
